const assert = require('assert');
const fs = require('fs');
const path = require('path');

const page = fs.readFileSync(path.join(__dirname, '..', 'app/v2/admin/page.tsx'), 'utf8');
const css = fs.readFileSync(path.join(__dirname, '..', 'app/v2/admin/admin.css'), 'utf8');
const auth = fs.readFileSync(path.join(__dirname, '..', 'app/v2/auth/page.tsx'), 'utf8');

assert(page.includes("localStorage.getItem('dc1_admin_token')"), 'v2 admin should guard with the admin token');
assert(page.includes('lockAdminSession'), 'v2 admin should expose a local session lock action');
assert(page.includes('loadRequestRef'), 'v2 admin should track in-flight load generations');
assert(page.includes('const isCurrentLoad'), 'v2 admin should gate stale load completion');
assert(page.includes("localStorage.removeItem('dc1_admin_token')"), 'v2 admin lock should clear the local admin token');
assert(page.includes("setState('missing-key')"), 'v2 admin lock should return the page to the missing-key state');
assert(page.includes('/v2/auth?role=admin&method=apikey&redirect=/v2/admin'), 'v2 admin should send missing auth to v2 admin sign-in');
assert(page.includes('/admin/dashboard'), 'v2 admin should load the verified admin dashboard API');
assert(page.includes('/admin/payments/audit?limit=40'), 'v2 admin should load the payments audit queue');
assert(page.includes('/admin/health'), 'v2 admin should load system health');
assert(page.includes('health?.capacity?.reason'), 'v2 admin should read the admin health capacity reason');
assert(page.includes('capacityReasonCopy'), 'v2 admin should render machine-readable capacity reasons as operator copy');
assert(page.includes('capacityGateCards'), 'v2 admin should derive capacity gate cards from health/fleet evidence');
assert(page.includes('Live capacity reason'), 'v2 admin should expose the live serving blocker reason in launch readiness');
assert(page.includes('no verified serving provider'), 'v2 admin should name the zero-serving-capacity reason');
assert(page.includes('heartbeat, endpoint reachability, earned inference, or model coverage'), 'v2 admin should explain which serving gate is blocking public capacity');
assert(page.includes('/admin/security/summary'), 'v2 admin should load security summary');
assert(page.includes('/admin/metrics'), 'v2 admin should load operational metrics for launch readiness');
assert(page.includes('/admin/demand'), 'v2 admin should load read-only demand signals for launch readiness');
assert(page.includes('/admin/providers?page=0&limit=200'), 'v2 admin should load provider supply context');
assert(page.includes('/admin/providers/approval-queue?limit=100'), 'v2 admin should load provider approval queue context');
assert(page.includes('/admin/fleet/health'), 'v2 admin should load earned fleet health');
assert(page.includes('/admin/fleet/alerts'), 'v2 admin should load fleet alerts');
assert(page.includes('/admin/fleet/probe-evidence?limit=50'), 'v2 admin should load canonical probe evidence');
assert(page.includes('/admin/finance/reconciliation?days=7'), 'v2 admin should load finance reconciliation');
assert(page.includes('/admin/errors?limit=20'), 'v2 admin should load recent error context');
assert(page.includes('/admin/control-plane/signals?limit=5'), 'v2 admin should load control-plane signals');
assert(page.includes('/admin/incidents/feed?hours=24&limit=8'), 'v2 admin should load the merged incident timeline feed');
assert(page.includes('/admin/audit?limit=8'), 'v2 admin should load recent admin audit entries');
assert(page.includes('/mission/overview'), 'v2 admin should load mission overview context');
assert(page.includes('/mission/tasks?status=todo,in_progress,blocked,review'), 'v2 admin should load open mission tasks');
assert(page.includes('/mission/assignees'), 'v2 admin should load the human and agent roster');
assert(page.includes('/mission/goals'), 'v2 admin should load mission goals');
assert(page.includes('/mission/pulse?hours=24'), 'v2 admin should load the 24h mission pulse');
assert(page.includes('/admin/access/policy'), 'v2 admin should load the access governance policy');
assert(page.includes('/admin/notifications/posture'), 'v2 admin should load notification posture instead of raw notification config');
assert(page.includes('/admin/support/contacts?limit=12'), 'v2 admin should load saved support contact submissions');
assert(page.includes('/admin/renters?page=1&limit=12'), 'v2 admin should load a bounded renter support sample');
assert(page.includes('/admin/jobs?limit=12'), 'v2 admin should load recent jobs for support triage');
assert(page.includes('/admin/payments?limit=12'), 'v2 admin should load recent payments for support context');
assert(page.includes('Operator brief'), 'v2 admin should expose a top-level operator brief');
assert(page.includes('operatorBriefItems'), 'v2 admin should derive operator brief items from loaded operational evidence');
assert(page.includes('primaryBrief'), 'v2 admin should pick the highest-priority operator brief item');
assert(page.includes('Today’s operating posture'), 'v2 admin should label the operator brief as the daily operating posture');
assert(page.includes('Serving proof is the sprint blocker'), 'v2 admin should elevate serving proof when public capacity is not ready');
assert(page.includes('Operator brief is read-only prioritization'), 'v2 admin should keep the operator brief read-only');
assert(page.includes('buildTasks'), 'v2 admin should synthesize an ops inbox');
assert(page.includes('buildReadinessChecks'), 'v2 admin should synthesize a launch readiness board');
assert(page.includes('agentMode'), 'v2 admin should model agent permission classes per task');
assert(page.includes('#launch'), 'v2 admin should expose founder launch readiness as a primary rail section');
assert(page.includes('Founder go / no-go'), 'v2 admin should label launch readiness as a founder decision layer');
assert(page.includes('Launch readiness'), 'v2 admin should expose a launch readiness section');
assert(page.includes('publicCapacityReady'), 'v2 admin should derive public capacity readiness from real fleet evidence');
assert(page.includes('launchBlockers'), 'v2 admin should compute launch blockers from operational evidence');
assert(page.includes('demandModelKeys'), 'v2 admin should normalize read-only demand signals');
assert(page.includes('Do not claim live marketplace capacity'), 'v2 admin should block public live-capacity claims when earned serving capacity is absent');
assert(page.includes('v2 launch readiness is read-only'), 'v2 admin should keep launch readiness read-only');
assert(page.includes('does not trigger provider repair, payments, deploys, or control-plane runs'), 'v2 admin should state that launch readiness has no mutation side effects');
assert(page.includes('#serving-recovery'), 'v2 admin should expose serving recovery as a primary rail section');
assert(page.includes('Serving recovery'), 'v2 admin should expose a serving recovery workflow');
assert(page.includes('buildServingRecoveryItem'), 'v2 admin should derive serving recovery actions from fleet evidence');
assert(page.includes('ProbeEvidencePayload'), 'v2 admin should type canonical probe evidence payloads');
assert(page.includes('probeEvidenceRows'), 'v2 admin should normalize canonical probe evidence rows');
assert(page.includes('probeFocusCopy'), 'v2 admin should map backend recovery focus codes into bilingual operator copy');
assert(page.includes('buildServingRecoveryItemFromProbe'), 'v2 admin should derive serving recovery actions from canonical probe evidence');
assert(page.includes('servingRecoveryRows'), 'v2 admin should render serving recovery rows');
assert(page.includes('hasProbeEvidence'), 'v2 admin should treat an empty canonical probe response as available evidence');
assert(page.includes('probeEvidence?.summary?.endpoint_reachable != null'), 'v2 admin should preserve zero endpoint-reachable counts from canonical evidence');
assert(page.includes('probeEvidence?.summary?.inference_blocked != null'), 'v2 admin should preserve zero inference-blocked counts from canonical evidence');
assert(page.includes('servingRecoveryPreview'), 'v2 admin should render a bounded serving recovery preview');
assert(page.includes('servingProbeEvidenceAge'), 'v2 admin should show the latest probe evidence timestamp or fallback source');
assert(page.includes('Canonical probe evidence'), 'v2 admin should label canonical probe evidence as the recovery source');
assert(page.includes('Serving proof packet'), 'v2 admin should expose a serving proof packet for the next provider target');
assert(page.includes('pickServingProofTarget'), 'v2 admin should choose a focused provider target from canonical probe evidence');
assert(page.includes('buildServingProofChecklist'), 'v2 admin should derive a route/inference/model proof checklist');
assert(page.includes('ServingHandoffCard'), 'v2 admin should type provider recovery handoff cards');
assert(page.includes('buildServingHandoffCards'), 'v2 admin should derive provider recovery handoffs from canonical probe evidence');
assert(page.includes('servingHandoffCards'), 'v2 admin should render the selected provider handoff packet');
assert(page.includes('Provider recovery handoff'), 'v2 admin should expose a provider recovery handoff packet');
assert(page.includes('copy-ready evidence note'), 'v2 admin handoff should include a copy-ready mission evidence note');
assert(page.includes('verified console'), 'v2 admin handoff should name the verified console for recovery evidence');
assert(page.includes('No daemon restart, WireGuard edit, endpoint edit, routing change, or public marketplace language change happens from this v2 packet'), 'v2 admin handoff should state its serving recovery mutation boundary');
assert(page.includes('Route proof'), 'v2 admin should show route proof separately from heartbeat state');
assert(page.includes('Inference proof'), 'v2 admin should show earned-inference proof separately from endpoint reachability');
assert(page.includes('Model proof'), 'v2 admin should show model alias/cache proof separately from route proof');
assert(page.includes('Publication proof'), 'v2 admin should keep public provider_count publication behind all proof gates');
assert(page.includes('verified_online=1, provider_count > 0'), 'v2 admin should state concrete serving proof exit criteria');
assert(page.includes('servingInferenceProbeBlocked'), 'v2 admin should summarize endpoint-reachable providers that still fail earned inference');
assert(page.includes('Inference timeout'), 'v2 admin should classify timeout-based earned probe failures');
assert(page.includes('Run /v1/models and a one-token inference from the VPS'), 'v2 admin should tell operators how to verify earned serving state');
assert(page.includes('v2 serving recovery is read-only'), 'v2 admin should keep serving recovery read-only');
assert(page.includes('agents may collect probe evidence'), 'v2 admin should allow agents to collect probe evidence without executing repairs');
assert(page.includes('daemon restarts, tunnel changes, endpoint edits, routing changes, and public capacity flips stay outside v2'), 'v2 admin should keep serving recovery mutation actions out of v2');
[
  '/admin/providers/${providerId}/restart',
  '/admin/providers/${providerId}/repair',
  '/admin/providers/${providerId}/endpoint',
  '/admin/providers/${providerId}/wireguard',
  '/admin/providers/${providerId}/routing',
].forEach((unsafePath) => {
  assert(!page.includes(unsafePath), `v2 admin serving recovery should not call unsafe provider repair mutation path: ${unsafePath}`);
});
assert(page.includes('#runbooks'), 'v2 admin should expose runbooks as a primary rail section');
assert(page.includes('Runbook queue'), 'v2 admin should expose a founder runbook queue');
assert(page.includes('runbookSteps'), 'v2 admin should derive runbook steps from loaded operational evidence');
assert(page.includes('Keep public capacity gated'), 'v2 admin should provide a public-capacity gating runbook');
assert(page.includes('Clear provider approval queue'), 'v2 admin should provide a provider approval runbook');
assert(page.includes('Assign money blockers'), 'v2 admin should provide a finance blocker runbook');
assert(page.includes('Triage incident evidence'), 'v2 admin should provide an incident handoff runbook');
assert(page.includes('Harden mission write gate'), 'v2 admin should provide an access/agent write gate runbook');
assert(page.includes('v2 runbooks are decision support for humans and agents'), 'v2 admin should keep runbooks as decision support');
assert(page.includes('repairs, money movement, deploys, provider actions, and control-plane writes stay in verified consoles'), 'v2 admin should state runbook mutation boundaries');
assert(page.includes('Guarded write'), 'v2 admin should expose guarded-write policy language');
assert(page.includes('Task envelope'), 'v2 admin should describe the future agent action envelope');
assert(page.includes('No verified serving capacity'), 'v2 admin should expose earned-serving capacity as an operational blocker');
assert(page.includes('read-only'), 'v2 admin should label the operational readiness board as read-only');
assert(page.includes('#fleet'), 'v2 admin should expose fleet readiness as a primary rail section');
assert(page.includes('Fleet blockers'), 'v2 admin should expose the fleet blocker section');
assert(page.includes('fleetProviderRows'), 'v2 admin should normalize fleet-health provider rows');
assert(page.includes('fleetProviderBlockers'), 'v2 admin should derive provider readiness blockers');
assert(page.includes('fleetProviderSeverity'), 'v2 admin should classify provider blocker severity');
assert(page.includes('endpoint reachable'), 'v2 admin should show endpoint reachability as a fleet readiness gate');
assert(page.includes('earned online'), 'v2 admin should show earned-online verification as a fleet readiness gate');
assert(page.includes('WireGuard stale'), 'v2 admin should surface WireGuard freshness blockers');
assert(page.includes('heartbeat critical'), 'v2 admin should surface stale heartbeat blockers');
assert(page.includes('no cached models'), 'v2 admin should surface model coverage blockers');
assert(page.includes('v2 fleet readiness is read-only'), 'v2 admin should keep fleet operations read-only');
assert(!page.includes('/admin/providers/pause'), 'v2 admin should not call provider pause from the fleet readiness surface');
assert(!page.includes('/admin/providers/resume'), 'v2 admin should not call provider resume from the fleet readiness surface');
assert(page.includes('Approval desk'), 'v2 admin should expose a native provider approval desk');
assert(page.includes('guarded write'), 'v2 admin should label provider approval decisions as guarded writes');
assert(page.includes('ApprovalDecisionResult'), 'v2 admin should type approval decision responses');
assert(page.includes('ApprovalDecisionEnvelope'), 'v2 admin should type provider approval decision envelopes');
assert(page.includes('buildApprovalDecisionEnvelopes'), 'v2 admin should derive provider approval decision envelopes');
assert(page.includes('Provider approval decision envelope'), 'v2 admin should render provider approval decision envelopes');
assert(page.includes('human approval'), 'v2 admin approval envelopes should label human approval');
assert(page.includes("method: 'PATCH'"), 'v2 admin provider decisions should use the audited PATCH path');
assert(page.includes('/approval-decision'), 'v2 admin should call the immutable provider approval decision endpoint');
assert(page.includes('reason.length < 8'), 'v2 admin should require a clear rejection reason before rejecting a provider');
assert(page.includes('Add at least 8 characters of rejection reason'), 'v2 admin should explain provider rejection readiness');
assert(page.includes('#finance'), 'v2 admin should expose finance as a primary rail section');
assert(page.includes('Finance review'), 'v2 admin should expose the finance review section');
assert(page.includes('refundReviewRows'), 'v2 admin should render refund request rows from the payment audit feed');
assert(page.includes('payoutReviewRows'), 'v2 admin should render provider payout rows from the payment audit feed');
assert(page.includes('billingExceptionRows'), 'v2 admin should render billing exception rows from the payment audit feed');
assert(page.includes('autoTopupIssueRows'), 'v2 admin should render auto-top-up issue rows from the payment audit feed');
assert(page.includes('financeQueueTotal'), 'v2 admin should summarize the finance review queue total');
assert(page.includes('FinanceHandoffCard'), 'v2 admin should type money review handoff cards');
assert(page.includes('buildFinanceHandoffCards'), 'v2 admin should derive money review handoffs from loaded finance evidence');
assert(page.includes('financeHandoffCards'), 'v2 admin should render the finance handoff packet');
assert(page.includes('Money review handoff'), 'v2 admin should expose a money review handoff packet');
assert(page.includes('Payments console'), 'v2 admin finance handoff should name the verified payments console');
assert(page.includes('copy-ready evidence note'), 'v2 admin finance handoff should include a copy-ready evidence note');
assert(page.includes('No refund approval, refund rejection, payout sync, balance edit, credit grant, payment confirmation, or auto-top-up retry happens from this v2 packet'), 'v2 admin finance handoff should state its money mutation boundary');
assert(page.includes('v2 finance is review-only for now'), 'v2 admin should keep finance money actions review-only');
assert(page.includes('Review payouts'), 'v2 admin should keep payout review anchored inside the v2 finance section');
assert(!page.includes('/admin/payments/refund-requests/${'), 'v2 admin should not call refund approve/reject endpoints directly');
assert(!page.includes('/admin/payouts/${'), 'v2 admin should not call payout mutation endpoints directly');
assert(page.includes('#support'), 'v2 admin should expose support operations as a primary rail section');
assert(page.includes('Support desk'), 'v2 admin should expose the customer support operations section');
assert(page.includes('supportContactRows'), 'v2 admin should normalize support contact rows');
assert(page.includes('renterSupportRows'), 'v2 admin should normalize renter support rows');
assert(page.includes('jobSupportRows'), 'v2 admin should normalize job support rows');
assert(page.includes('paymentSupportRows'), 'v2 admin should normalize payment support rows');
assert(page.includes('supportQueueTotal'), 'v2 admin should summarize the support queue total');
assert(page.includes('v2 support is read-only'), 'v2 admin should keep support operations read-only');
assert(page.includes('agents may summarize contacts'), 'v2 admin should allow agents to summarize support evidence');
assert(page.includes('suspensions, credits, balance edits, job cancel/requeue, refunds, and key rotation stay in verified consoles'), 'v2 admin should keep customer-support mutation actions out of the support desk');
[
  '/admin/renters/${renterId}/suspend',
  '/admin/renters/${renterId}/unsuspend',
  '/admin/renters/${renterId}/credit',
  '/admin/renters/${renterId}/balance',
  '/admin/renters/${renterId}/rotate-key',
  '/admin/jobs/${jobId}/cancel',
  '/admin/jobs/${jobId}/requeue',
  '/admin/payments/${paymentId}/refund',
].forEach((unsafePath) => {
  assert(!page.includes(unsafePath), `v2 admin support desk should not call unsafe customer-support mutation path: ${unsafePath}`);
});
assert(page.includes('Team operating layer'), 'v2 admin should expose the team operating layer');
assert(page.includes('Mission control'), 'v2 admin should expose the mission control section');
assert(page.includes('guarded actions'), 'v2 admin should label mission control as guarded actions');
assert(page.includes('human / agent roster'), 'v2 admin should summarize human and agent assignees');
assert(page.includes('Task ownership'), 'v2 admin should show mission task ownership');
assert(page.includes('Action desk'), 'v2 admin should expose the mission action desk');
assert(page.includes('MissionActionEnvelope'), 'v2 admin should type the mission action envelope preview');
assert(page.includes('buildMissionActionEnvelopes'), 'v2 admin should derive mission action envelopes from selected task inputs');
assert(page.includes('Mission action envelope'), 'v2 admin should render the mission action envelope before guarded writes');
assert(page.includes('strict guarded write'), 'v2 admin should label strict mission action envelopes');
assert(page.includes('legacy admin write'), 'v2 admin should label legacy mission action envelopes');
assert(page.includes('strict write gate'), 'v2 admin should label the strict mission write gate in the action desk');
assert(page.includes('legacy write gate'), 'v2 admin should label the legacy mission write gate in the action desk');
assert(page.includes('Evidence note'), 'v2 admin should require an evidence note for mission actions');
assert(page.includes('Add at least 8 characters of evidence'), 'v2 admin should explain mission evidence-note readiness');
assert(page.includes('Move status'), 'v2 admin should allow guarded mission status moves');
assert(page.includes('Reassign'), 'v2 admin should allow guarded mission reassignment');
assert(page.includes('Add note'), 'v2 admin should allow guarded mission notes');
assert(page.includes('postJson'), 'v2 admin should use an explicit helper for guarded mission POST actions');
assert(page.includes('closing_comment'), 'v2 admin should send a closing comment when completing mission tasks');
assert(page.includes('/mission/tasks/${taskId}`'), 'v2 admin should PATCH the existing guarded mission task route');
assert(page.includes('/mission/tasks/${taskId}/reassign'), 'v2 admin should POST reassignment to the existing guarded mission route');
assert(page.includes('/mission/tasks/${taskId}/comments'), 'v2 admin should POST comments to the existing guarded mission route');
assert(page.includes("source: 'v2_admin'"), 'v2 admin mission notes should identify the v2 admin source');
assert(page.includes("kind: 'admin_note'"), 'v2 admin mission notes should identify admin-note comments');
assert(page.includes('Delete and create controls stay out of this surface'), 'v2 admin should keep mission delete/create controls out of the action desk');
assert(page.includes('Access governance'), 'v2 admin should expose access governance');
assert(page.includes('Role and agent gates'), 'v2 admin should label the role and agent gate section');
assert(page.includes('missionStrictWrites'), 'v2 admin should render strict-vs-legacy mission write posture');
assert(page.includes('legacy writes'), 'v2 admin should surface the legacy write posture when strict mode is disabled');
assert(page.includes('strict writes'), 'v2 admin should surface the strict write posture when enabled');
assert(page.includes('missionWritePolicy'), 'v2 admin should display the backend mission write policy');
assert(page.includes('agentWriteState'), 'v2 admin should display guarded agent write readiness');
assert(page.includes('limited v2 mission actions exposed'), 'v2 admin should state that only limited mission actions are exposed');
assert(page.includes('Notification routing'), 'v2 admin should expose notification routing posture');
assert(page.includes('Human and agent alerts'), 'v2 admin should label notification routing for humans and agents');
assert(page.includes('notificationNotifyState'), 'v2 admin should display agent notify readiness');
assert(page.includes('redacted destination only'), 'v2 admin should state that notification destinations are redacted');
assert(page.includes('v2 admin shows notification posture only'), 'v2 admin should keep notification writes outside the v2 surface');
assert(!page.includes('/admin/notifications/config'), 'v2 admin should not consume raw notification config');
assert(page.includes('Action ledger'), 'v2 admin should expose an action ledger before the raw audit trail');
assert(page.includes('ActionLedgerItem'), 'v2 admin should type action ledger rows');
assert(page.includes('buildActionLedger'), 'v2 admin should derive the ledger from already-loaded evidence');
assert(page.includes('admin audit + mission pulse'), 'v2 admin ledger should identify its two evidence sources');
assert(page.includes('agent touches'), 'v2 admin ledger should summarize agent-visible action history');
assert(page.includes('The action ledger is read-only from /admin/audit and /mission/pulse'), 'v2 admin ledger should state its read-only source contract');
assert(page.includes('It does not create tasks, approve providers, replay writes, send notifications, move money, or repair providers'), 'v2 admin ledger should state its mutation boundary');
assert(page.includes('#action-ledger'), 'v2 admin should expose the action ledger in the rail');
assert(page.includes('Recent audit trail'), 'v2 admin should expose a recent audit trail');
assert(page.includes('Accountability layer'), 'v2 admin should label audit as accountability context');
assert(page.includes('adminAuditRows'), 'v2 admin should normalize admin audit payloads');
assert(page.includes('adminAuditEntries'), 'v2 admin should render recent admin audit entries');
assert(page.includes('No recent entries'), 'v2 admin should render an empty audit state');
assert(page.includes('#incidents'), 'v2 admin should expose incident command as a primary rail section');
assert(page.includes('Incident command'), 'v2 admin should expose an incident command section');
assert(page.includes('incidentTimelineRows'), 'v2 admin should normalize merged incident timeline rows');
assert(page.includes('errorEventRows'), 'v2 admin should normalize recent error rows');
assert(page.includes('controlPlaneSignalRows'), 'v2 admin should normalize control-plane signal rows');
assert(page.includes('incidentSeverity'), 'v2 admin should classify incident severity');
assert(page.includes('controlSignalSeverity'), 'v2 admin should classify control-plane signal severity');
assert(page.includes('v2 incident command is read-only'), 'v2 admin should keep incident command read-only');
assert(page.includes('Control-plane snapshots, prewarm runs, run-cycle triggers, and daemon repair stay in verified consoles'), 'v2 admin should explain why incident actions stay out of v2');
assert(!page.includes('/admin/control-plane/signals/snapshot'), 'v2 admin should not call control-plane snapshot actions');
assert(!page.includes('/admin/control-plane/prewarm/run'), 'v2 admin should not call control-plane prewarm actions');
assert(!page.includes('/admin/control-plane/run-cycle'), 'v2 admin should not call control-plane run-cycle actions');
assert(!page.includes('/admin/providers/sweep-stale'), 'v2 admin launch readiness should not trigger stale-provider sweeps');
assert(!page.includes('/admin/providers/${providerId}/preload-model'), 'v2 admin launch readiness should not trigger provider preload actions');
assert(!page.includes('/admin/payments/confirm-topup'), 'v2 admin runbooks should not trigger payment confirmation');
assert(!page.includes('/admin/notifications/test'), 'v2 admin runbooks should not trigger notification test sends');
assert(!page.includes('href="/admin'), 'v2 admin visible links should not send operators to legacy admin pages');
assert(!page.includes("href: '/admin"), 'v2 admin generated action links should stay inside v2 sections');
assert(!page.includes('href={`/admin'), 'v2 admin provider drilldowns should stay inside v2 sections');
assert(!page.includes('Current console'), 'v2 admin rail should not advertise the legacy admin console as a primary action');
assert(!page.includes('isLegacyAdminHref'), 'v2 admin should not need legacy admin link handling for primary actions');
assert(!page.includes('prefetch={false}'), 'v2 admin should not carry legacy prefetch suppression for primary actions');
assert(page.includes("method: 'POST'"), 'v2 admin command center should perform guarded mission POST actions');
assert(!page.includes("method: 'DELETE'"), 'v2 admin command center should not delete mission/admin entities');
assert(!page.includes("postJson<{ task?: MissionTask }>(`/mission/tasks`"), 'v2 admin should not create mission tasks');
assert(!page.includes('/approve`'), 'v2 admin should not use the legacy provider approve shortcut');
assert(!page.includes('/reject`'), 'v2 admin should not use the legacy provider reject shortcut');
assert(!page.includes("router.push('/login"), 'v2 admin should not route missing operators to the old login page');

assert(auth.includes("redirect=/v2/admin"), 'v2 auth admin link should land on the v2 admin command center');
assert(!auth.includes("redirect=/admin'"), 'v2 auth should not default admin sign-in back to the old admin console');

assert(css.includes('.v2-admin'), 'v2 admin should have scoped styles');
assert(css.includes('.admin-lock'), 'v2 admin should style the session lock button');
assert(css.includes('.readiness-board'), 'v2 admin should style the readiness board');
assert(css.includes('.operator-brief'), 'v2 admin should style the operator brief');
assert(css.includes('.operator-brief-grid'), 'v2 admin should style the operator brief grid');
assert(css.includes('.operator-brief-primary'), 'v2 admin should style the primary operator brief');
assert(css.includes('.launch-readiness'), 'v2 admin should style launch readiness');
assert(css.includes('.launch-summary-grid'), 'v2 admin should style launch readiness summary metrics');
assert(css.includes('.launch-gate-list'), 'v2 admin should style launch readiness gates');
assert(css.includes('.launch-gate'), 'v2 admin should style launch gate rows');
assert(css.includes('.launch-policy'), 'v2 admin should style the launch read-only policy');
assert(css.includes('.capacity-blocker'), 'v2 admin should style the live capacity blocker packet');
assert(css.includes('.capacity-gate-grid'), 'v2 admin should style the capacity gate cards');
assert(css.includes('.serving-recovery'), 'v2 admin should style serving recovery');
assert(css.includes('.serving-recovery-summary'), 'v2 admin should style serving recovery summary metrics');
assert(css.includes('.serving-recovery-grid'), 'v2 admin should style serving recovery panels');
assert(css.includes('.serving-recovery-card'), 'v2 admin should style serving recovery cards');
assert(css.includes('.serving-recovery-blockers'), 'v2 admin should style serving recovery blocker chips');
assert(css.includes('.serving-recovery-policy'), 'v2 admin should style the serving recovery read-only policy');
assert(css.includes('.serving-proof'), 'v2 admin should style the serving proof packet');
assert(css.includes('.serving-proof-checklist'), 'v2 admin should style the serving proof checklist');
assert(css.includes('.serving-proof-exit'), 'v2 admin should style the serving proof exit criteria');
assert(css.includes('.serving-handoff'), 'v2 admin should style the provider recovery handoff');
assert(css.includes('.serving-handoff-grid'), 'v2 admin should style provider recovery handoff cards');
assert(css.includes('.serving-handoff-card'), 'v2 admin should style individual recovery handoff cards');
assert(css.includes('.runbook-queue'), 'v2 admin should style the runbook queue');
assert(css.includes('.runbook-grid'), 'v2 admin should style runbook cards');
assert(css.includes('.runbook-card'), 'v2 admin should style individual runbook cards');
assert(css.includes('.runbook-policy'), 'v2 admin should style the runbook read-only policy');
assert(css.includes('.fleet-readiness'), 'v2 admin should style fleet readiness');
assert(css.includes('.fleet-summary-grid'), 'v2 admin should style fleet summary gates');
assert(css.includes('.mission-action-envelope'), 'v2 admin should style the mission action envelope');
assert(css.includes('.fleet-readiness-grid'), 'v2 admin should style fleet provider and alert panels');
assert(css.includes('.fleet-provider-card'), 'v2 admin should style fleet provider blocker cards');
assert(css.includes('.fleet-blockers'), 'v2 admin should style fleet blocker chips');
assert(css.includes('.approval-desk'), 'v2 admin should style the provider approval desk');
assert(css.includes('.approval-envelope-grid'), 'v2 admin should style provider approval decision envelopes');
assert(css.includes('.approval-actions'), 'v2 admin should style approval decision actions');
assert(css.includes('.finance-review'), 'v2 admin should style finance review');
assert(css.includes('.finance-summary-grid'), 'v2 admin should style finance summary cards');
assert(css.includes('.finance-handoff'), 'v2 admin should style the money review handoff');
assert(css.includes('.finance-handoff-grid'), 'v2 admin should style money handoff cards');
assert(css.includes('.finance-handoff-card'), 'v2 admin should style individual money handoff cards');
assert(css.includes('.finance-review-grid'), 'v2 admin should style finance review cards');
assert(css.includes('.finance-row'), 'v2 admin should style finance rows');
assert(css.includes('.finance-policy'), 'v2 admin should style the finance review-only policy');
assert(css.includes('.support-ops'), 'v2 admin should style support operations');
assert(css.includes('.support-summary-grid'), 'v2 admin should style support summary metrics');
assert(css.includes('.support-grid'), 'v2 admin should style support cards');
assert(css.includes('.support-card'), 'v2 admin should style individual support cards');
assert(css.includes('.support-row'), 'v2 admin should style support evidence rows');
assert(css.includes('.support-policy'), 'v2 admin should style the support read-only policy');
assert(css.includes('.mission-control'), 'v2 admin should style mission control');
assert(css.includes('.mission-summary-grid'), 'v2 admin should style mission summary metrics');
assert(css.includes('.mission-roster'), 'v2 admin should style the mission roster');
assert(css.includes('.mission-action-desk'), 'v2 admin should style the mission action desk');
assert(css.includes('.mission-action-grid'), 'v2 admin should style mission action controls');
assert(css.includes('.mission-action-buttons'), 'v2 admin should style mission action buttons');
assert(css.includes('.access-governance'), 'v2 admin should style access governance');
assert(css.includes('.access-grid'), 'v2 admin should style the access governance cards');
assert(css.includes('.access-ladder'), 'v2 admin should style the access permission ladder');
assert(css.includes('.notification-posture'), 'v2 admin should style notification posture');
assert(css.includes('.notification-grid'), 'v2 admin should style notification routing cards');
assert(css.includes('.notification-policy'), 'v2 admin should style the notification policy note');
assert(css.includes('.action-ledger'), 'v2 admin should style the action ledger');
assert(css.includes('.action-ledger-summary'), 'v2 admin should style action ledger summary metrics');
assert(css.includes('.action-ledger-row'), 'v2 admin should style action ledger rows');
assert(css.includes('.action-ledger-meta'), 'v2 admin should style action ledger actor and target metadata');
assert(css.includes('.action-ledger-policy'), 'v2 admin should style the action ledger read-only policy');
assert(css.includes('.audit-trail'), 'v2 admin should style the audit trail');
assert(css.includes('.audit-list'), 'v2 admin should style audit entries');
assert(css.includes('.audit-entry'), 'v2 admin should style individual audit cards');
assert(css.includes('.incident-command'), 'v2 admin should style incident command');
assert(css.includes('.incident-summary-grid'), 'v2 admin should style incident summary metrics');
assert(css.includes('.incident-command-grid'), 'v2 admin should style incident command evidence panels');
assert(css.includes('.incident-row'), 'v2 admin should style incident rows');
assert(css.includes('.control-signal'), 'v2 admin should style control-plane signal rows');
assert(css.includes('.incident-policy'), 'v2 admin should style the incident read-only policy');
assert(css.includes('.lane-grid'), 'v2 admin should style operational lanes');
assert(css.includes('min-height: 100dvh'), 'v2 admin should use dynamic viewport height for mobile stability');
assert(!css.includes('h-screen'), 'v2 admin should not use unstable h-screen layouts');

console.log('v2 admin static checks passed');
