const assert = require('assert');
const fs = require('fs');
const path = require('path');

const page = fs.readFileSync(path.join(__dirname, '..', 'app/v2/admin/page.tsx'), 'utf8');
const css = fs.readFileSync(path.join(__dirname, '..', 'app/v2/admin/admin.css'), 'utf8');
const auth = fs.readFileSync(path.join(__dirname, '..', 'app/v2/auth/page.tsx'), 'utf8');

assert(page.includes("localStorage.getItem('dc1_admin_token')"), 'v2 admin should guard with the admin token');
assert(page.includes('/v2/auth?role=admin&method=apikey&redirect=/v2/admin'), 'v2 admin should send missing auth to v2 admin sign-in');
assert(page.includes('/admin/dashboard'), 'v2 admin should load the verified admin dashboard API');
assert(page.includes('/admin/payments/audit?limit=40'), 'v2 admin should load the payments audit queue');
assert(page.includes('/admin/health'), 'v2 admin should load system health');
assert(page.includes('/admin/security/summary'), 'v2 admin should load security summary');
assert(page.includes('/admin/providers?page=0&limit=200'), 'v2 admin should load provider supply context');
assert(page.includes('/admin/providers/approval-queue?limit=100'), 'v2 admin should load provider approval queue context');
assert(page.includes('/admin/fleet/health'), 'v2 admin should load earned fleet health');
assert(page.includes('/admin/fleet/alerts'), 'v2 admin should load fleet alerts');
assert(page.includes('/admin/finance/reconciliation?days=7'), 'v2 admin should load finance reconciliation');
assert(page.includes('/admin/errors?limit=20'), 'v2 admin should load recent error context');
assert(page.includes('/admin/control-plane/signals?limit=5'), 'v2 admin should load control-plane signals');
assert(page.includes('/admin/audit?limit=8'), 'v2 admin should load recent admin audit entries');
assert(page.includes('/mission/overview'), 'v2 admin should load mission overview context');
assert(page.includes('/mission/tasks?status=todo,in_progress,blocked,review'), 'v2 admin should load open mission tasks');
assert(page.includes('/mission/assignees'), 'v2 admin should load the human and agent roster');
assert(page.includes('/mission/goals'), 'v2 admin should load mission goals');
assert(page.includes('/mission/pulse?hours=24'), 'v2 admin should load the 24h mission pulse');
assert(page.includes('/admin/access/policy'), 'v2 admin should load the access governance policy');
assert(page.includes('/admin/notifications/posture'), 'v2 admin should load notification posture instead of raw notification config');
assert(page.includes('buildTasks'), 'v2 admin should synthesize an ops inbox');
assert(page.includes('buildReadinessChecks'), 'v2 admin should synthesize a launch readiness board');
assert(page.includes('agentMode'), 'v2 admin should model agent permission classes per task');
assert(page.includes('Guarded write'), 'v2 admin should expose guarded-write policy language');
assert(page.includes('Task envelope'), 'v2 admin should describe the future agent action envelope');
assert(page.includes('No verified serving capacity'), 'v2 admin should expose earned-serving capacity as an operational blocker');
assert(page.includes('read-only'), 'v2 admin should label the operational readiness board as read-only');
assert(page.includes('Approval desk'), 'v2 admin should expose a native provider approval desk');
assert(page.includes('guarded write'), 'v2 admin should label provider approval decisions as guarded writes');
assert(page.includes('ApprovalDecisionResult'), 'v2 admin should type approval decision responses');
assert(page.includes("method: 'PATCH'"), 'v2 admin provider decisions should use the audited PATCH path');
assert(page.includes('/approval-decision'), 'v2 admin should call the immutable provider approval decision endpoint');
assert(page.includes('reason.length < 8'), 'v2 admin should require a clear rejection reason before rejecting a provider');
assert(page.includes('Team operating layer'), 'v2 admin should expose the team operating layer');
assert(page.includes('Mission control'), 'v2 admin should expose the mission control section');
assert(page.includes('guarded actions'), 'v2 admin should label mission control as guarded actions');
assert(page.includes('human / agent roster'), 'v2 admin should summarize human and agent assignees');
assert(page.includes('Task ownership'), 'v2 admin should show mission task ownership');
assert(page.includes('Action desk'), 'v2 admin should expose the mission action desk');
assert(page.includes('strict write gate'), 'v2 admin should label the strict mission write gate in the action desk');
assert(page.includes('legacy write gate'), 'v2 admin should label the legacy mission write gate in the action desk');
assert(page.includes('Evidence note'), 'v2 admin should require an evidence note for mission actions');
assert(page.includes('Move status'), 'v2 admin should allow guarded mission status moves');
assert(page.includes('Reassign'), 'v2 admin should allow guarded mission reassignment');
assert(page.includes('Add note'), 'v2 admin should allow guarded mission notes');
assert(page.includes('postJson'), 'v2 admin should use an explicit helper for guarded mission POST actions');
assert(page.includes('closing_comment'), 'v2 admin should send a closing comment when completing mission tasks');
assert(page.includes('/mission/tasks/${taskId}`'), 'v2 admin should PATCH the existing guarded mission task route');
assert(page.includes('/mission/tasks/${taskId}/reassign'), 'v2 admin should POST reassignment to the existing guarded mission route');
assert(page.includes('/mission/tasks/${taskId}/comments'), 'v2 admin should POST comments to the existing guarded mission route');
assert(page.includes("source: 'v2_admin'"), 'v2 admin mission notes should identify the v2 admin source');
assert(page.includes("kind: 'admin_note'"), 'v2 admin mission notes should identify admin-note comments');
assert(page.includes('Delete and create controls stay out of this surface'), 'v2 admin should keep mission delete/create controls out of the action desk');
assert(page.includes('Access governance'), 'v2 admin should expose access governance');
assert(page.includes('Role and agent gates'), 'v2 admin should label the role and agent gate section');
assert(page.includes('missionStrictWrites'), 'v2 admin should render strict-vs-legacy mission write posture');
assert(page.includes('legacy writes'), 'v2 admin should surface the legacy write posture when strict mode is disabled');
assert(page.includes('strict writes'), 'v2 admin should surface the strict write posture when enabled');
assert(page.includes('missionWritePolicy'), 'v2 admin should display the backend mission write policy');
assert(page.includes('agentWriteState'), 'v2 admin should display guarded agent write readiness');
assert(page.includes('limited v2 mission actions exposed'), 'v2 admin should state that only limited mission actions are exposed');
assert(page.includes('Notification routing'), 'v2 admin should expose notification routing posture');
assert(page.includes('Human and agent alerts'), 'v2 admin should label notification routing for humans and agents');
assert(page.includes('notificationNotifyState'), 'v2 admin should display agent notify readiness');
assert(page.includes('redacted destination only'), 'v2 admin should state that notification destinations are redacted');
assert(page.includes('v2 admin shows notification posture only'), 'v2 admin should keep notification writes outside the v2 surface');
assert(!page.includes('/admin/notifications/config'), 'v2 admin should not consume raw notification config');
assert(page.includes('Recent audit trail'), 'v2 admin should expose a recent audit trail');
assert(page.includes('Accountability layer'), 'v2 admin should label audit as accountability context');
assert(page.includes('adminAuditRows'), 'v2 admin should normalize admin audit payloads');
assert(page.includes('adminAuditEntries'), 'v2 admin should render recent admin audit entries');
assert(page.includes('No recent entries'), 'v2 admin should render an empty audit state');
assert(page.includes('Current console'), 'v2 admin should keep a link to the existing safe admin console');
assert(page.includes('isLegacyAdminHref'), 'v2 admin should classify old admin console links');
assert(page.includes('prefetch={false}'), 'v2 admin should not prefetch legacy admin console links');
assert(page.includes("method: 'POST'"), 'v2 admin command center should perform guarded mission POST actions');
assert(!page.includes("method: 'DELETE'"), 'v2 admin command center should not delete mission/admin entities');
assert(!page.includes("postJson<{ task?: MissionTask }>(`/mission/tasks`"), 'v2 admin should not create mission tasks');
assert(!page.includes('/approve`'), 'v2 admin should not use the legacy provider approve shortcut');
assert(!page.includes('/reject`'), 'v2 admin should not use the legacy provider reject shortcut');
assert(!page.includes("router.push('/login"), 'v2 admin should not route missing operators to the old login page');

assert(auth.includes("redirect=/v2/admin"), 'v2 auth admin link should land on the v2 admin command center');
assert(!auth.includes("redirect=/admin'"), 'v2 auth should not default admin sign-in back to the old admin console');

assert(css.includes('.v2-admin'), 'v2 admin should have scoped styles');
assert(css.includes('.readiness-board'), 'v2 admin should style the readiness board');
assert(css.includes('.approval-desk'), 'v2 admin should style the provider approval desk');
assert(css.includes('.approval-actions'), 'v2 admin should style approval decision actions');
assert(css.includes('.mission-control'), 'v2 admin should style mission control');
assert(css.includes('.mission-summary-grid'), 'v2 admin should style mission summary metrics');
assert(css.includes('.mission-roster'), 'v2 admin should style the mission roster');
assert(css.includes('.mission-action-desk'), 'v2 admin should style the mission action desk');
assert(css.includes('.mission-action-grid'), 'v2 admin should style mission action controls');
assert(css.includes('.mission-action-buttons'), 'v2 admin should style mission action buttons');
assert(css.includes('.access-governance'), 'v2 admin should style access governance');
assert(css.includes('.access-grid'), 'v2 admin should style the access governance cards');
assert(css.includes('.access-ladder'), 'v2 admin should style the access permission ladder');
assert(css.includes('.notification-posture'), 'v2 admin should style notification posture');
assert(css.includes('.notification-grid'), 'v2 admin should style notification routing cards');
assert(css.includes('.notification-policy'), 'v2 admin should style the notification policy note');
assert(css.includes('.audit-trail'), 'v2 admin should style the audit trail');
assert(css.includes('.audit-list'), 'v2 admin should style audit entries');
assert(css.includes('.audit-entry'), 'v2 admin should style individual audit cards');
assert(css.includes('.lane-grid'), 'v2 admin should style operational lanes');
assert(css.includes('min-height: 100dvh'), 'v2 admin should use dynamic viewport height for mobile stability');
assert(!css.includes('h-screen'), 'v2 admin should not use unstable h-screen layouts');

console.log('v2 admin static checks passed');
